export const JokesActionTypes = {
  GET_FETCH_URL: 'GET_FETCH_URL',

  FETCH_JOKE : 'FETCH_JOKE',

  FETCH_CATEGORIES : 'FETCH_CATEGORIES',

  SELECT_CATEGORY: 'SELECT_CATEGORY',

  GET_JOKE_QUERY: 'GET_JOKE_QUERY',
}