export const JokesActionTypes = {
  GET_FETCH_URL: 'GET_FETCH_URL',
  FETCH_JOKE : 'FETCH_JOKE',
  FETCH_CATEGORIES : 'FETCH_CATEGORIES',
  GET_SEARCH_QUERY: 'GET_SEARCH_QUERY',
  IS_LOADED: 'IS_LOADED'
}